🔀 :: (#104) config authorization/authentication
team-xquare/v1-service-application pull request #105
Opened 2022-06-15 00:18 UTC by parksangwoo1617

close #104

2022-06-15 10:26 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
> +        authorities.add(new SimpleGrantedAuthority(userRole.name()));
Role은 `ROLE_` prefix 붙이는게 어떤가요?

2022-06-15 10:42 UTC, leeseojune53 reviewed
필터는 api gateway 맹글어지고 등록?

2022-06-15 10:49 UTC, parksangwoo1617 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
> +        authorities.add(new SimpleGrantedAuthority(userRole.name()));
아하 알겠습니당

2022-06-15 10:50 UTC, parksangwoo1617 commented
> 필터는 api gateway 맹글어지고 등록?

엄 등록을 깜박했네

2022-06-15 10:51 UTC, leeseojune53 commented
필터 걸어놓고 나중에 연결하면 permition 설정 하믄 될듯

2022-06-15 10:54 UTC, parksangwoo1617 commented
굳굳

2022-06-15 11:11 UTC, leeseojune53 requested changes

2022-06-15 11:11 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenFilter.java
> +    private final TokenProvider TokenProvider;
변수 명 tokenProvider로 변경

2022-06-15 11:15 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
> +@Slf4j
이거 붙인 이유가 뭐에요?

2022-06-15 11:25 UTC, jeongjiwoo0522 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
> +@Slf4j
나도 궁금

2022-06-15 11:25 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
> +@Slf4j
로그 찍으려고 붙였다가 까먹은거아닌감?

2022-06-15 11:26 UTC, parksangwoo1617 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenFilter.java
> +    private final TokenProvider TokenProvider;
이건 머노

2022-06-15 11:26 UTC, parksangwoo1617 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
> +@Slf4j
아 저거 전에 토큰 직접 파싱해서 쓰기로 했을 때 서준이가 예외처리 한다고 달았었는데 지금은 필요없어졌네요 뺄게용

2022-06-15 11:27 UTC, parksangwoo1617 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
> +@Slf4j
예외처리할 때 log 찍으려고 달았던 거였어용

2022-06-15 11:29 UTC, parksangwoo1617 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
> +        for (String aut : userAuthorities) {
aut 말씀하시는 건가요

2022-06-15 11:29 UTC, jeongjiwoo0522 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
> +        for (String aut : userAuthorities) {
그렇죠

2022-06-15 23:34 UTC, parksangwoo1617 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
> +        for (String aut : userAuthorities) {
aut 말씀하시는 건가요

2022-06-15 23:35 UTC, parksangwoo1617 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenProvider.java
> +        for (String aut : userAuthorities) {
넹

2022-06-15 23:46 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenFilter.java
> +public class TokenFilter extends OncePerRequestFilter {
토큰에 대한 내용이 없으니 TokenFilter 대신 다른 내용으로 바꾸는거 어떨까요?

2022-06-15 23:46 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java
> +        builder.addFilterBefore(tokenFilter, UsernamePasswordAuthenticationFilter.class);
addFilterAt은 어떨까요? UsernamePasswordAuthetnticationFilter가 굳이 필요해보이진 않는데

2022-06-16 00:16 UTC, parksangwoo1617 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenFilter.java
> +public class TokenFilter extends OncePerRequestFilter {
usernamePasswordAuthenticationToken을 만든다는 의미에서 그냥 두었었는데

2022-06-16 00:17 UTC, parksangwoo1617 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenFilter.java
> +public class TokenFilter extends OncePerRequestFilter {
뭐로 바꿀까요

2022-06-16 00:17 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/TokenFilter.java
> +public class TokenFilter extends OncePerRequestFilter {
음.. AuthenticationFilter 정도로 하면 될 것 같아요

2022-06-16 02:44 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java
> +        builder.addFilterBefore(tokenFilter, UsernamePasswordAuthenticationFilter.class);
addFilterAt을 해도 오버라이드가 되진않아요
근데 before나 at을 하면 해당 필터보다 앞에 들어가서 인증정보를 맹글어서 UsernamePasswordAuthenticationFilter가 안돌아가는걸로 기억합니당

2022-06-16 02:46 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/FilterConfig.java
> +        builder.addFilterBefore(tokenFilter, UsernamePasswordAuthenticationFilter.class);
아하 그렇네요 그럼 상관없을 것 같습니다

2022-06-16 05:25 UTC, leeseojune53 approved these changes

2022-06-16 08:05 UTC, jeongjiwoo0522 approved these changes

2022-06-16 09:58 UTC, merged