♻️ :: refactoring
team-xquare/v1-service-application pull request #154
Opened 2022-09-23 05:34 UTC by parksangwoo1617

close #148

2022-09-23 05:50 UTC, jhhong0509 requested changes
p2) 이게 리팩토링임?

2022-09-23 05:50 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/security/SecurityConfig.java
>                  .antMatchers(HttpMethod.POST, "/signup").permitAll()
p3) 얘는 뭐임?
그리고 `/applicaitons` prefix 안붙여도 됨?

2022-09-23 06:33 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-09-23 12:54 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-09-27 12:46 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/SignupSettingRequest.java
> +}
@NoArgs나 @AllArgs 안붙여도 되요?

2022-09-28 12:37 UTC, lyutvs approved these changes

2022-09-28 12:38 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/SignupSettingRequest.java
> +}
근데 자바인데도 붙여줘요?

2022-09-28 12:41 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/SignupSettingRequest.java
> +}
?? 뭔소리야 기본생성자는 원래 자바 특징인데

2022-09-28 12:42 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/presentation/dto/request/SignupSettingRequest.java
> +}
다른 생성자 없으면 기본 생성자 붙음

2022-09-28 12:42 UTC, jhhong0509 approved these changes

2022-09-28 13:13 UTC, merged