🔀 :: (#165) cloud config 설정
team-xquare/v1-service-application pull request #166
Opened 2022-10-25 02:40 UTC by eogus2513

close #165

2022-10-25 02:41 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-25 02:45 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-25 02:46 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-25 03:26 UTC, jhhong0509 requested changes
p2) Dockerfile이랑 github도 바꿔야 오류 안날듯

2022-10-25 04:08 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-25 04:35 UTC, jhhong0509 reviewed
p3) 아 맞다 나는 귀찮아서 그냥 config-server에 모든 설정 정보를 박아뒀는데 좋은 습관은 아님
해당 서비스에서 사용되는 application.yml들은 그대로 두는게 좋음
예를 들어 `spring.jpa.datatabase`라는 값을 application.yml에 넣고싶으면
``` yaml
spring:
  jpa:
    database: ${xquare.database}
```
이런식으로 참조하는게 나음

2022-10-25 10:35 UTC, eogus2513 commented
> p3) 아 맞다 나는 귀찮아서 그냥 config-server에 모든 설정 정보를 박아뒀는데 좋은 습관은 아님 해당 서비스에서 사용되는 application.yml들은 그대로 두는게 좋음 예를 들어 `spring.jpa.datatabase`라는 값을 application.yml에 넣고싶으면
> 
> ```yaml
> spring:
>   jpa:
>     database: ${xquare.database}
> ```
> 
> 이런식으로 참조하는게 나음

그럼 config-server에는 어떤 정보를 넣어두면 좋아요?

2022-10-25 10:47 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-25 12:01 UTC, jhhong0509 commented
> 그럼 config-server에는 어떤 정보를 넣어두면 좋아요?

? 저기서 했던것처럼 xquare.database같은걸 cloud-config에 박아놓고 그걸 우리 서버 application.yml에서 참조

2022-10-25 23:23 UTC, jhhong0509 approved these changes

2022-10-26 01:43 UTC, jaemin05 approved these changes

2022-10-26 02:17 UTC, merged

2022-10-26 02:18 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃