🔀 :: (#192) 주말 외출 현황 엑셀 다운로드 API
team-xquare/v1-service-application pull request #193
Opened 2023-03-19 05:11 UTC by min56

2023-03-19 05:52 UTC, eogus2513 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +
여기 줄바꿈 삭제 해야 할듯

2023-03-19 05:52 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +        Row row1 = sheet.createRow(0);
row1이면 어떤 뜻인지 잘모르겠음 다른걸로 바꿔야 할듯

2023-03-19 05:52 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +            row.createCell(cellNum+5).setCellValue(weekendPicnicExcelElement.getArrangement());
여기 정렬이 필요해 보임

2023-03-19 05:52 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +    public Workbook createWorkBook2(Workbook workbook) {
여기도 method명 바꿔야 할듯

2023-03-19 05:52 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +        row.createCell(6).setCellValue("동행인");
이거 for문으로 바꾸면 좋을 거 같은데..

2023-03-19 14:29 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +    public Workbook createWeekendOutingListWorkHook() {
Q) Hook의 뜻이 뭔가요?

2023-03-19 14:29 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/AdminPicnicController.java
> +        String filename = "주말외출명단.xlsx";
p3) usecase layer에서 filename을 지정하는 방식이 더 좋을 것 같습니다.

2023-03-19 14:36 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
아쉬운 부분은 코드가 한 눈에 전혀 들어오지 않음
역할별로 method를 쪼개거나, 도메인별로 쪼갰으면 그나마 괜찮았을 것 같은데.

현재 요구사항이 대충IsAcceptance에 따라 외출 / 외출 대기로 나눠져있는 것으로 보이는데, 해당 부분을 따로 method로 만든이유를 모르겠음

2023-03-19 14:36 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
@min56 코드 개선 힌트를 주자면 값이 다르다고해서 Entity가 다른게 아니고(현재 코드 상), 분리할거였으면 동일한 역할을 분리해야함(값 입력)
근데 현재 코드는 XSSFWorkbook을 생성하는 부분은 한 곳에있고 이러면 코드 중복을 해결할 때 쉽게 보이지 않음

2023-03-19 14:36 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
결국 내 코멘트의 핵심은 XSSF생성하는 곳과 값을 넣는걸 분리하고, `createWeekendOutingListWorkHook`함수가 `createWeekendOutingWaitingListWorkBook`에 의존성 가지지않게 분리하라는거임
이러면 어떻게 개선해야할지 보일걸

2023-03-19 14:37 UTC, leeseojune53 requested changes

2023-03-19 14:37 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
힘내십쇼

2023-03-19 14:47 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +    public Workbook createWeekendOutingListWorkHook() {
workBook으로 작성하려다가 오타가 난 것 같습니다 수정 완료했습니다.

2023-03-20 00:57 UTC, eogus2513 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +        List<UUID> userIdList = picnicRepositorySpi.findUserIdByToday();
이렇게 하면 나중에 Request URL이 길어지면 'HTTP line is larger than 4096 bytes' 이렇게 에러가 뜨는데 그걸 미연에 방지하기 위해서 user쪽에서 학생만 가지고 오는 API가 있어서 그걸로 처리하면 더 좋을 듯

2023-03-20 10:17 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
피드백 주신대로 리팩토링을 해보긴 했는데 더 리팩토링 할 부분이 없는지 확인 부탁드립니다

2023-03-20 13:51 UTC, min56 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +        List<UUID> userIdList = picnicRepositorySpi.findUserIdByToday();
userIdList를 UserClientImpl에 있는 queryAllUser로 변경했습니다.

2023-03-20 14:33 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +        Sheet sheet2 = workbook.createSheet("주말외출대기현황");
p3) 네이밍은 @eogus2513께서도 몇 번 언급해주셨던 것 같아요.
네이밍이 명확하지 않으면 추후에 유지보수할 때 모든 코드를 다 읽어봐야하니 조금 더 고민해보는걸 추천드립니다 :)

2023-03-20 14:33 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +                picnicApi.weekendPicnicExcel().getWeekendPicnicList().stream().filter(picnic -> picnic.getIsAcceptance() == false).toList();
이거 2시간 막히기 전에 열면 실력이 안늘거예요

2023-03-21 00:13 UTC, eogus2513 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +                .collect(Collectors.toMap(PicnicUserElement::getUserId, user -> user, (userId, user) -> user, HashMap::new));
User정보를 굳이 2번 가지고 온 이유가 궁금해

2023-03-21 06:43 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +        }
이 부분도 setBodyRow같은 메소드로 빼면 의도를 표현하기 좋을듯
근데 cellNum이란 변수는 왜 있는겨?

2023-03-21 06:43 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +        cellStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
얘 정적으로 박아놓고 greyCellStyle 같은 이름의 변수에 담아두면 의미 표현할 때 좋을듯

2023-03-21 06:43 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/AdminPicnicController.java
> +        String filename = "주말외출명단.xlsx";
난 개인적으로 반대임
usecase의 재사용성이 떨어질 우려가 있고, 
그리고 'Client한테서 요청을 받고, 응답해주는 것'에 관한 책임은 Presentation에 있는게 옳다고 생각함

2023-03-22 02:29 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/AdminPicnicController.java
> +        String filename = "주말외출명단.xlsx";
그러네 시트 이름부터가 usecase에 박혀있구나
그냥 코드 안보고 내가 생각했던건 조회 범위를 파라미터로 받아서 사용한다면 '주말외출명단' 이란 이름이 다른 Presentation에선 적절하지 않을 수 있다고 생각했음(평일 외출 기록 조회를 한다던가 등등)
그리고 유연성 관련 내용 말고도 이건 presentation 계층의 책임이 맞긴 함
@min56 이 부분은 수정하지 말고 냅두는 대신 위에 나랑 서준이가 대화한 내용 바탕으로 어떤게 더 좋은 코드인지 고민해봐

2023-03-22 14:35 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/presentation/AdminPicnicController.java
> +        String filename = "주말외출명단.xlsx";
그럼 현재처럼 presentatino단에 놔두겠습니다.

2023-03-25 03:07 UTC, min56 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +                .collect(Collectors.toMap(PicnicUserElement::getUserId, user -> user, (userId, user) -> user, HashMap::new));
HTTP line is larger than 4096 bytes에러를 방지하기 위해 코드를 변경했을 때에는 user정보를 두 번 가져오고 있는 걸 확안하지 못했던 것 같습니다. 한 번만 가져오도록 변경 완료했습니다

2023-03-26 12:34 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +        }
setBodyRow메소드로 분리 완료했습니다. cellNum이란 변수는 Excel 값 생성시 Cell의 위치를 한칸씩 늘려 header에 맞는 값을 위치시키기 위해서 CellNum이란 변수를 만들었습니다.

2023-03-27 02:02 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +        }
1 + 1, 2 + 1, 3 + 1 ...
이런식으로 표현하는것보단 차라리
2, 3, 4, ...
이게 낫지 않을까?

2023-03-27 23:52 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +                picnicApi.weekendPicnicExcel().getWeekendPicnicList().stream().filter(picnic -> picnic.getIsAcceptance() == false).toList();
죄송합니다. 커멘트 확인을 좀 늦게 확인하게 되었는데 어떤 식으로 개선할지 고민하다보니 resolve가 늦어졌습니다..

2023-03-27 23:59 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/infrastructure/excel/WeekendPicnicExcel.java
> +                picnicApi.weekendPicnicExcel().getWeekendPicnicList().stream().filter(picnic -> picnic.getIsAcceptance() == false).toList();
그런 부분이면 천천히 해도돼요 🙃

2023-03-28 09:13 UTC, jaemin05 approved these changes

2023-03-28 14:30 UTC, leeseojune53 requested changes

2023-03-28 14:30 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +                .collect(Collectors.toMap(StudentElement::getUserId, user -> user, (userId, user) -> user, HashMap::new));
p1) 학교에 갑자기 학생이 1,000,000명이 된다면 이 코드가 정상 동작할지 한 번 고민해보면 좋을 것 같아요.

2023-03-30 11:28 UTC, min56 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +                .collect(Collectors.toMap(StudentElement::getUserId, user -> user, (userId, user) -> user, HashMap::new));
Stream API에서 제공하는 collect가 데이터량이 방대해졌을 때 속도이슈가 발생할수도 있다는 걸 알게 되어서 for loop문으로 변경 했습니다.

2023-03-30 14:06 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +                .collect(Collectors.toMap(StudentElement::getUserId, user -> user, (userId, user) -> user, HashMap::new));
음.. 내 의도는 그쪽 수정이 아니었어요
전체 유저를 들고와도 사용하는 유저 정보는 몇 개 안될 수도 있으니까, 사용하는 정보들만 들고오는 방법에 대한 이야기였습니다 :)

2023-03-30 14:22 UTC, min56 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +                .collect(Collectors.toMap(StudentElement::getUserId, user -> user, (userId, user) -> user, HashMap::new));
기존의 코드가 필요한 user정보만 userId로 요청해서 가져오는 로직이였는데 그런 방식으로 요청을 했을 경우 Request URL이 길어지면서 HTTP line is larger than 4096 bytes에러가 발생한다는 대현 선배님이 커멘트를 반영해서 전체 유저를 조회해서 필요한 유저정보만 사용하는 것으로 변경했습니다 제가 잘 이해한 건지 잘 모르겠지만 다시 필요한 유저 정보만 가져오게 된다면 같은 에러가 나지 않을까라고 생각합니다.

2023-04-03 14:16 UTC, leeseojune53 requested changes

2023-04-03 14:16 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +                .collect(Collectors.toMap(StudentElement::getUserId, user -> user, (userId, user) -> user, HashMap::new));
@eogus2513 보통 문제가 있으면 원인을 해결해야하는거 아닌가요? 전체 유저 리스트는 임시적인 조치인거고 장기적으로보면 필요한 유저만 가져오는게 맞을 것 같은데.
4096Byte 이상으로 늘리는게 가장 좋아보이고, 안된다면 다른 방안을 찾아야할 것 같습니다.

2023-04-03 14:16 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +                .collect(Collectors.toMap(StudentElement::getUserId, user -> user, (userId, user) -> user, HashMap::new));
그냥 간단하게 이게 최선인가? 라는 질문을 해보셨으면 좋겠습니다

2023-04-03 23:56 UTC, eogus2513 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +                .collect(Collectors.toMap(StudentElement::getUserId, user -> user, (userId, user) -> user, HashMap::new));
> @eogus2513 보통 문제가 있으면 원인을 해결해야하는거 아닌가요? 전체 유저 리스트는 임시적인 조치인거고 장기적으로보면 필요한 유저만 가져오는게 맞을 것 같은데. 4096Byte 이상으로 늘리는게 가장 좋아보이고, 안된다면 다른 방안을 찾아야할 것 같습니다.

말씀하신대로 임시적인 조치이고 해결방법을 계속 찾아보고 있습니다. 최대한 빨리 찾아내서 해결하도록 하겠습니다..

2023-04-04 13:47 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/service/PicnicApiImpl.java
> +                .collect(Collectors.toMap(StudentElement::getUserId, user -> user, (userId, user) -> user, HashMap::new));
@min56 해당부분 이슈 생성하고 머지하심될 것 같습니다

2023-04-04 13:47 UTC, leeseojune53 approved these changes

2023-04-04 14:18 UTC, merged