🔀 :: (#194) 주말 외출 예약 신청&삭제
team-xquare/v1-service-application pull request #195
Opened 2023-03-20 13:32 UTC by jaemin05

close #194

2023-03-20 13:37 UTC, eogus2513 requested changes
분리해서 PR 올려주세요!

2023-03-20 14:21 UTC, leeseojune53 requested changes

2023-03-20 14:21 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        LocalTime endTime = LocalTime.of(23, 0);
p4) 얘는 동일하게 사용되는 것 같아서 위쪽에 static final로 따로 빼도 될듯요

2023-03-20 14:21 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        LocalTime nowTime = LocalTime.now();
p4) currentTime

2023-03-20 14:21 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        }
Q) 요 조건 설명 가능할까요? 금요일 제한만 있으면 될 것 같은데, 사감실 요청인가요??

2023-03-20 14:21 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +    cancelWeekendPicnic(UUID picnicReservationId) {
p4) 줄바꿈

2023-03-20 14:21 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        picnicReservationRepositorySpi.cancelWeekendPicnic(picnicReservation.getId());
p3) picnicReservation을 사용한 이유는 노란 줄이 떠서 그런걸까요(가져오고 미사용)?
코드에 의도를 더 녹여내려면 isExist와 같은 method를 사용해서 체크한 후 service쪽에서 NotFound Exception throw 처리를 하는 것도 좋을 것 같아요 :)

2023-03-20 14:21 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        return new PicnicReservationListResponse(picnicReservationElementList);
한 번 더 고민해보는게 좋은 경험이될 것 같아요.
조금 더 직관적인 코드가 가능할 것 같습니다.

2023-03-20 14:21 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
p1) BaseEntity를 상속받아서 사용하는게 좋을 것 같습니다.

2023-03-21 00:21 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID userId;
이 부분에도 NotNull이 붙으면 더 좋을 거 같아요

2023-03-21 02:50 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        picnicReservationRepositorySpi.cancelWeekendPicnic(picnicReservation.getId());
네넵

2023-03-21 06:10 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID userId;
![image](https://user-images.githubusercontent.com/89118999/226530357-4a3772af-9abc-4d64-9429-423a88e6bd98.png)
BaseEntity 를 상속받게되면 userId가 필드값으로 있는데 해당 로직에 @NotNull 추가할까요?

2023-03-21 06:15 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        }
주말 외출 신청 예약할 경우에는 저녁 11시까지 신청을 받는다고 사감선생님께서 요청하셨습니다.
부모님께 외출한다는 sms 전송한다고 들었습니다.

2023-03-21 06:45 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID userId;
추가하면 더 좋을 거 같습니다!

2023-03-21 06:49 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
다른 얘기긴 한데 BaseEntity 이름 한 번 고민해보면 좋을듯
BaseEntity는 '모든 Entity의 부모 클래스일 것이다'라는 착각하게됨

2023-03-22 00:58 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +            throw CannotReservePicnicTimeException.EXCEPTION;
수정 완료했습니다.

2023-03-22 00:58 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        LocalTime endTime = LocalTime.of(23, 0);
수정 완료했습니다.

2023-03-22 00:58 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        LocalTime nowTime = LocalTime.now();
수정 완료했습니다.

2023-03-22 00:58 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +    cancelWeekendPicnic(UUID picnicReservationId) {
수정 완료했습니다.

2023-03-22 00:58 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        return new PicnicReservationListResponse(picnicReservationElementList);
수정 완료했습니다.

2023-03-22 00:59 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID userId;
수정 완료했습니다.

2023-03-22 00:59 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
BaseUserInfo로 고칠까요?

2023-03-22 01:35 UTC, eogus2513 approved these changes

2023-03-22 01:35 UTC, eogus2513 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +    static final LocalTime currentTIme = LocalTime.now();
이거 이렇게 해도 되나요?

2023-03-22 02:17 UTC, oliver37632 reviewed
예약 신청 토요일 일요일 따로 안 받나요?

2023-03-22 02:22 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
사실 개인적으로 BaseEntity 자체가 마음에 안드는 편이라
`@UuidId` 같은 어노테이션을 만드는건 어떰?

2023-03-22 02:43 UTC, jaemin05 commented
> 예약 신청 토요일 일요일 따로 안 받나요?

예악 금요일에 일괄적으로 받는걸로 알고 있습니다.

2023-03-22 11:23 UTC, oliver37632 approved these changes

2023-03-22 11:27 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +    static final LocalTime currentTIme = LocalTime.now();
저거 저렇게 하면 안되더라고요

2023-03-22 14:50 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
@jhhong0509 형님 
그렇다면 id만 어노테이션으로 만들고 userId와 date는 일반 컬럼으로 만들면 되나요?

2023-03-23 05:19 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
ㅖㅏ

2023-03-23 06:55 UTC, jhhong0509 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        if (day != DayOfWeek.FRIDAY) {
금요일에만 안되는거임?
목요일 / 토요일 / 일요일은?

2023-03-23 06:55 UTC, jhhong0509 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +            picnicReservationRepositorySpi.reserveWeekendPicnic(
동시성 문제

2023-03-23 07:17 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        if (day != DayOfWeek.FRIDAY) {
금요일에만 가능하도록 했습니다.

2023-03-24 01:34 UTC, jhhong0509 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        if (day != DayOfWeek.FRIDAY) {
ㅇㅎ

2023-03-24 03:14 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
@jhhong0509 형님 혹시 이렇게 하는 것이 맞을까요?
![image](https://user-images.githubusercontent.com/89118999/227415225-87432c95-fad1-4158-96f0-0fd4c19ec1fc.png)

2023-03-24 04:44 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
ㄴㄴ 이거 말고
Annotation 맹그는거 찾아보레이

2023-03-24 13:57 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        }
Q) 얘네 두 조건이 다른 Exception을 던지는 이유는 뭐야? 동일한 Exception을 던져도 된다면 if문 하나로 묶어서 처리하면 훨씬 가독성이 좋을 듯.

2023-03-24 13:57 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +    }
p3) 코드 정리 및 (정)상수 따로 빼주세요

2023-03-29 02:40 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
@jhhong0509 형님 
혹시 어떻게 하는지 잘 모르겠는데 도와주실 수 있으신가요..?

2023-03-29 02:42 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +            picnicReservationRepositorySpi.reserveWeekendPicnic(
Repository에 Lock 을 걸어 해결했습니다.

2023-03-29 02:43 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        }
넵 수정했습니다.

2023-03-29 09:43 UTC, jhhong0509 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +            picnicReservationRepositorySpi.reserveWeekendPicnic(
이상한데다 lock 건 것 같은데?

2023-03-29 09:43 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
ㄱㄷ 퇴근하고 봄

2023-03-29 10:44 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
넵 감사합니다

2023-03-29 10:45 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +            picnicReservationRepositorySpi.reserveWeekendPicnic(
다른 방법은 생각해보지 않았습니다..

2023-03-29 14:17 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
@jaemin05 cc @leeseojune53 불가능하네
클래스에 저 어노테이션들들 적용이 안됨
<img width="660" alt="image" src="https://user-images.githubusercontent.com/57659252/228567600-268cfa67-e4ed-47bf-8a74-bf4b5afc2ad8.png">

2023-03-29 14:18 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
그럼 BaseEntity 그대로 내버려둘까요?

2023-03-29 14:19 UTC, jhhong0509 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationEntity.java
> +    private UUID id;
예ㅏ

2023-03-29 14:20 UTC, jhhong0509 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +            picnicReservationRepositorySpi.reserveWeekendPicnic(
1. lock으로 해결이 불가능한건 아니지만 빡셀거임
2. lock 없이 해결할 방법은 있음

2023-03-29 14:24 UTC, jhhong0509 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +            picnicReservationRepositorySpi.reserveWeekendPicnic(
MySQL `ON DUPLICATE KEY UPDATE` 참고 ㄱ

2023-03-29 14:25 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +            picnicReservationRepositorySpi.reserveWeekendPicnic(
넵 감사합니다

2023-03-30 07:37 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +            picnicReservationRepositorySpi.reserveWeekendPicnic(
수정완료했습니다.

2023-04-04 03:15 UTC, jhhong0509 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +            picnicReservationRepositorySpi.reserveWeekendPicnic(
해결안됨

2023-04-06 10:40 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +            picnicReservationRepositorySpi.reserveWeekendPicnic(
@jhhong0509 형님 수정했습니다.

2023-04-07 00:04 UTC, lyutvs commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/presentation/PicnicReservationController.java
> +public class PicnicReservationController {
Delete 메소드는 어디있음??

2023-04-07 00:47 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/presentation/PicnicReservationController.java
> +public class PicnicReservationController {
생성과 삭제를 하나의 api에서 처리하는 로직이야.
body에서 Boolean 입력받아서 처리하는 로직이야

2023-04-07 00:55 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/presentation/PicnicReservationController.java
> +public class PicnicReservationController {
주말 급식 신청 로직이랑 똑같이 처리했어

2023-04-07 01:00 UTC, lyutvs approved these changes

2023-04-07 14:58 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/repository/PicnicReservationSpiImpl.java
> +        return picnicReservationEntityList.stream().map(picnicReservationMapper::picnicReservationEntityToDomain).collect(Collectors.toList());
여기는 DB에서 하는게 훨씬 성능도 좋고, 코드도 명확해질 것 같습니다.

2023-04-07 14:58 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        LocalDate friday = currentDate.with(TemporalAdjusters.next(DayOfWeek.FRIDAY));
여긴 합치는게 좋을 듯

2023-04-07 14:58 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationId.java
> +    private LocalDate date;
이건 외출을 나가는 날짜인지? date는 mysql의 예약어중 하나라서 되도록이면 다르고 명확하게 네이밍을 하는게 좋을 것 같습니다.

2023-04-07 14:58 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +                .filter(picnicReservation -> picnicReservation.getIsReserved().equals(true))
Q) 이건 DB에서 가져올 하지않은 이유는?

2023-04-07 15:03 UTC, leeseojune53 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +                .toList();
여기 코드 흐름을 보면 다음 금요일에 해당하는 date(뭔지 모르겠음)를 찾고, 거기서 userId만 가져와서 또 그걸 feign으로 쏘고, map에 넣어서 사용하는데 어떤 이유에서 요렇게 작성했는지 궁금함(너무 복잡해)
내 생각에는 user service에 요청을 날리는게 부담돼서 그런 것 같은데 latency를 보고 판단하면 좋을 듯

2023-04-10 14:46 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/repository/PicnicReservationSpiImpl.java
> +        return picnicReservationEntityList.stream().map(picnicReservationMapper::picnicReservationEntityToDomain).collect(Collectors.toList());
넵 수정했습니다!

2023-04-10 14:46 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +        LocalDate friday = currentDate.with(TemporalAdjusters.next(DayOfWeek.FRIDAY));
넵 수정했습니다!

2023-04-10 14:47 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/domain/PicnicReservationId.java
> +    private LocalDate date;
picnicReservationDate로 수정했습니다!

2023-04-10 14:47 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +                .filter(picnicReservation -> picnicReservation.getIsReserved().equals(true))
밑에 리뷰 수정하면서 같이 고쳤습니다!

2023-04-10 14:49 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +                .toList();
@leeseojune53 형님
생각해보니까 값을 가져올 때 신청한 유저만 가져오는 것이어서 바로 출력했습니다.

2023-04-11 02:19 UTC, jhhong0509 approved these changes

2023-04-11 02:19 UTC, jhhong0509 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +    static final LocalTime endTime = LocalTime.of(23, 0);
private도 붙여줘
그리고 static 변수 naming convention은 camel로 통일된거지?

2023-04-11 04:13 UTC, eogus2513 approved these changes

2023-04-11 04:15 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/presentation/PicnicReservationController.java
> +    }
개인적인 생각인데 주말 외출 예약은 201이 맞다고 생각하는데 업데이트는 201이 뭔가 부자연스러운데 200 어떨까요?

2023-04-11 04:20 UTC, jaemin05 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/reservation/presentation/PicnicReservationController.java
> +    }
저도 그렇게 생각합니다

2023-04-11 04:22 UTC, jaemin05 commented on application-domain/src/main/java/io/github/v1serviceapplication/reservation/service/PicnicReservationApiImpl.java
> +    static final LocalTime endTime = LocalTime.of(23, 0);
전부 대문자로 수정하겠습니다.

2023-04-13 07:42 UTC, merged