🔀 :: (#8) picnic Entity 추가 및 변경
team-xquare/v1-service-application pull request #203
Opened 2023-04-22 23:10 UTC by min56

전날 8:30부터 당일 11:30까지 외출 신청을 받는 것에 따라 엔티티 수정을 하였습니다.

picnicMapperImpl클래스를 새로 작성한 이유는 MapStruct를 사용하면 의도하지 않았던 필드에 매핑되는 경우가 있고 모델끼리의 관계가 복잡해지면 매핑 코드가 어려워질 수 있다는 글들을 보게 되었고 유지보수를 위해 코드의 일관성을 지키는 것이 좋을 것 같다고 생각해서 picnicMapperImpl클래스를 작성하게 되었습니다.

2023-04-23 00:26 UTC, jungho1209 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java
> +
요거 지워주세여

2023-04-23 02:54 UTC, eogus2513 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/Picnic.java
> +    private final LocalDateTime date;
Type이 LocalDateTime인데 date이면 헷갈릴 수 있다고 생각합니다.

2023-04-23 02:54 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java
> +                .where(picnicEntity.date.between(LocalDate.now().atStartOfDay(), LocalDateTime.of(LocalDate.now(), LocalTime.MAX).withNano(0)))
변수로 빼서 작성하면 가독성이 조금 더 좋아질 거 같아요

2023-04-23 02:54 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/PicnicEntity.java
> +    private LocalTime picnicAllowStartTime;
이 변수는 어떤 역할을 하나요?

2023-04-23 04:46 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/PicnicEntity.java
> +    private LocalTime picnicAllowStartTime;
사감 선생님이 허용하신 외출 시간을 저장하는 역할입니다

2023-04-23 08:12 UTC, min56 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnic/Picnic.java
> +    private final LocalDateTime date;
dateTime으로 변경했습니다

2023-04-23 14:44 UTC, leeseojune53 commented
@min56 issue number 수정 부탁드려요

2023-04-23 14:47 UTC, leeseojune53 requested changes

2023-04-23 14:47 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java
> +    private LocalDate date;
P2) MySQL 예약어와 겹치기도하고, 어떤 date를 나타내는건지 모르겠습니다. 조금 더 명확한 네이밍이 있으면 좋을 것 같아요

2023-04-23 23:44 UTC, min56 commented
> @min56 issue number 수정 부탁드려요 어느 프로젝트의 issue number인지 모르겠네유

Linear로 이슈를 파고 스마트 커밋이 되도록 issue number를 붙였습니다. 기존의 application의 8번 issueNumber와 겹쳐서 issue number가 제대로 붙여지지 않은 것 같습니다

2023-04-24 02:34 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java
> +    private LocalDate date;
createDate로 변경 완료 했습니다.

2023-04-24 13:11 UTC, leeseojune53 commented
> > @min56 issue number 수정 부탁드려요 어느 프로젝트의 issue number인지 모르겠네유
> 
> Linear로 이슈를 파고 스마트 커밋이 되도록 issue number를 붙였습니다. 기존의 application의 8번 issueNumber와 겹쳐서 issue number가 제대로 붙여지지 않은 것 같습니다

음.. 그러면 연동을 하는게 좋지않을까 싶은디

2023-04-26 03:04 UTC, eogus2513 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnicdatetime/DateTimeType.java
> +    PICNIC_ALLOW_END_TIME(LocalTime.of(20, 0));
이 값을 DB로 하면 어떨까요? 바뀔일이 많이 없긴 하지만 사감선생님께서 수정하실 때 바로 반영 될 수 있으면 더 좋을 거 같아서요

2023-04-27 14:13 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/domain/repository/PicnicRepositorySpiImpl.java
> +        System.out.println(LocalDateTime.of(LocalDate.now(), picnicRequestEndTime));
죄송합니다 테스트 과정에서 실수로 지우지 못하고 커밋 한 거 같습니다 제거 완료했습니다

2023-04-27 23:36 UTC, min56 commented on application-domain/src/main/java/io/github/v1serviceapplication/picnicdatetime/DateTimeType.java
> +    PICNIC_ALLOW_END_TIME(LocalTime.of(20, 0));
DB값이 변경 될 때 코드 변경없이 반영되는 것이 저도 좋다고 생각해서 변경완료했습니다

2023-04-28 02:16 UTC, jhhong0509 approved these changes

2023-04-28 02:16 UTC, jhhong0509 commented on application-infrastructure/src/main/resources/application.yml
> +    password: hkokim0309
요거 실수로 커밋한 것 같은데 원복해줘

2023-04-28 04:34 UTC, min56 commented on application-infrastructure/src/main/resources/application.yml
> +    password: hkokim0309
넵 죄송합니다 테스트할 때 값을 변경한 걸 확인 못하고 올려버린 것 같습니다..

2023-04-29 03:20 UTC, eogus2513 approved these changes

2023-04-29 03:20 UTC, eogus2513 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnic/mapper/PicnicMapperImpl.java
> +public class PicnicMapperImpl implements PicnicMapper{
이 부분 정렬 부탁드립니다

2023-04-30 13:51 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicdatetime/domain/repository/PicnicTimeRepositorySpiImpl.java
> +                .fetchOne();
여기는 querydsl을 사용한 이유가 있나요?

2023-04-30 13:51 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java
>      @NotNull
~~BaseEntity에 해당 역할을 똑같이 수행하는 date라는 필드가 있는데, 추가하는 것 보다 프로젝트 전체적으로 수정하는게 좋을 것 같습니다~~
해당 부분을 수정해서 사용하는게 좋을듯하네용

2023-04-30 13:51 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
>                          .build())
이 부분 코드를 더 깔끔하게 할 수 있을 것 같습니다 :)

2023-04-30 13:51 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseEntity.java
> -    private LocalDate date;
여기를 지우고 각 Entity에 date를 추가한 이유가 있을까요?
또, 관련해서 DB Table 수정한 DDL은 어디에 있나요?

2023-04-30 13:51 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicdatetime/domain/PicnicTimeEntity.java
> +public class PicnicTimeEntity {
Q) PicnicTimeEntity는 느낌상 여러 시간대를 선택할 수 있을 것 같은데, 위 코드들을 보면 타입별로 단 하나의 값만 있는 것 같아서 어떻게 사용하는건지 질문드립니다

2023-05-01 07:00 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicdatetime/domain/repository/PicnicTimeRepositorySpiImpl.java
> +                .fetchOne();
간단한 쿼리문은 보통 jpa를 통해서 처리하는 것으로 알고 있지만 다른 선배님들이 짜신 코드를 보고 간단한 쿼리문도 querydsl로 처리하신 걸 보고 코드 일관성을 지키는게 좋을 것 같다고 생각해서 querydsl로 사용했습니다

2023-05-01 13:30 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseEntity.java
> -    private LocalDate date;
PicnicEntity가 BaseEntity클래스를 상속받아 date를 사용하고 있었는데 date의 타입을 LocalDateTime으로 변경시켜주면서 BaseEntity를 상속받는 클래스들에서 date를 사용하고 있어서 따로 추가해주었습니다. 따로 추가해주는 것보다 각 entity클래스마다 작성해주는 것보다 BaseDateEntity를 만들어 상속받게 해주는 것으로 바꾸는 것이 더 좋을 것 같습니다

2023-05-01 13:31 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseEntity.java
> -    private LocalDate date;
DB table 수정한 DDL은 DDL은 정의어로 알고 있는데 그 DDL이 어디에 있냐는 건 정확히 어떤 걸 물으신건지 이해가 잘 안가는 것 같습니다..

2023-05-01 13:35 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/StayEntity.java
>      @NotNull
BaseDateEntity를 만들어서 상속하도록 변경했습니다

2023-05-01 13:36 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/picnicdatetime/domain/PicnicTimeEntity.java
> +public class PicnicTimeEntity {
PicnicTimeEntity는 Enum타입 하나 별로 시간 값 하나씩만 있는 것이 맞습니다 네이밍이 좀 더 정확하도록 변경하겠습니다.

2023-05-03 13:53 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/global/entity/BaseEntity.java
> -    private LocalDate date;
스퀘어 노션에 따로 페이지를 만들어서 정리해놓겠습니다

2023-05-03 13:58 UTC, min56 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
>                          .build())
@leeseojune53 죄송합니다 현재 이 기능을 급하게 개발해야 해서 강제 머지를 해야할 것 같습니다 추후 코드 수정 완료하겠습니다

2023-05-03 13:59 UTC, merged

2023-05-07 16:53 UTC, leeseojune53 commented on application-infrastructure/src/main/java/io/github/v1serviceapplication/domain/stay/domain/repository/StayRepositorySpiImpl.java
>                          .build())
요쪽 수정하는 PR올리면 코멘트에 한 번 언급해줘요 :)